### PR TITLE
Sync with upstream @ v0.6.2

### PR DESCRIPTION
**Pull request by dtrifiro**
Related changes:
- Dockerfile.rocm.ubi: add setuptools-scm build dependency (see https://github.com/vllm-project/vllm/pull/4738)-
- Dockerfile.ubi: use `COPY . .` to copy full repo when bulilding (related to `setuptools-scm` update aswell)

Changelog: https://github.com/vllm-project/vllm/releases/tag/v0.6.2

### CODE REVIEW

**Comment by RH-steve-grubb** [comment]
This would be good to merge.

**Comment by RH-steve-grubb** [comment]
I did a grep for VLLM_FA_CMAKE_GPU_ARCHES. It is only referenced in the Dockerfile. No code or makefiles reference it. Searching the whole internet only finds that Dockerfile in vllm. I don't think it's used or Google would have found it in many places.

**Comment by dtrifiro** [comment]
> 
I did a grep for VLLM_FA_CMAKE_GPU_ARCHES. It is only referenced in the Dockerfile. No code or makefiles reference it. Searching the whole internet only finds that Dockerfile in vllm. I don't think it's used or Google would have found it in many places.

You're right @RH-steve-grubb, in recent builds a custom flash-attention fork has been introduced https://github.com/vllm-project/flash-attention, which is cloned in `vllm`'s `CMakelists.txt` and then built.

See https://github.com/vllm-project/flash-attention/blob/main/CMakeLists.txt#L40

**Pull request merged**
