### PR TITLE
ROCm build for UBI

### PR DESCRIPTION
**Pull request by Xaenalt**
Needs some additional testing

### CODE REVIEW

**Comment by dtrifiro** [comment]
Is this a duplicate of https://github.com/opendatahub-io/vllm/pull/142?

**Comment by vaibhavjainwiz** [comment]
> Is this a duplicate of #142?

I closed the #142

**Comment by vaibhavjainwiz** [comment]
I am merging it because it build process become cyclic with https://github.com/openshift/release/pull/56346.

Rehearse-ask job of Openshift-CI changes for rcom build expecting Dockerfile.rocm.ubi be a part of code base where as this PR expecting openshift-ci is properly setup.

**Comment by dtrifiro** [comment]
@vaibhavjainwiz  #142  is still open. Also, why were the build definitions merged before this Dockerfile was merged?

**Pull request merged**
