### PR TITLE
sync release with IBM/release

### PR DESCRIPTION
**Pull request by dtrifiro**
this includes ibm_main with bd23984 (ray as optional dependency) cherry-picked on top of it

### CODE REVIEW

**Comment by dtrifiro** [comment]
@heyselbi  @Xaenalt if we merge this, we'll end up having the `stable` tag point to `ibm_release` (an ephemeral branch based on  `ibm_main` with a few commits cherry-picked on top of it).

If we instead follow the approach proposed here: https://github.com/red-hat-data-services/rhods-devops-infra/pull/46/files#r1608003340 then we should be creating a new `ibm_release` branch in this repo and have the `release` branch just sync to `main`.

**Comment by heyselbi** [comment]
@dtrifiro I think it needs a rebase, and retest after rebase, no?

**Comment by dtrifiro** [comment]
@heyselbi no, this should be good to merge, unless there's new changes on IBM/release and/or we want to include something new from ibm_main

**Pull request merged**
