### PR TITLE
[CI/Build] fix: update setup.py to differentiate between fork and upstream

### PR DESCRIPTION
**Pull request by nathan-weinberg**
This PR updates `setup.py` to differentiate between the ODH and upstream vLLM projects. This work would be a prereq to making this into an independent PyPI package.

### CODE REVIEW

**Review by Xaenalt — APPROVED** [review]

**Review by dtrifiro — APPROVED** [review]

**Comment by dtrifiro** [comment]
Please note that this will fail until #93 is merged

**Comment by dtrifiro** [comment]
This is creating issues with our downstream `vllm-tgis-adapter`, which depends on `vllm` https://github.com/opendatahub-io/vllm-tgis-adapter/blob/main/pyproject.toml#L29.

I'm reverting this for now, until we figure out some way to mitigate this

**Comment by nathan-weinberg** [comment]
@dtrifiro Couldn't you just update the line https://github.com/opendatahub-io/vllm-tgis-adapter/blob/main/pyproject.toml#L29 to be `vllm-odh`?

**Comment by dtrifiro** [comment]
@nathan-weinberg yes, we could do that, but that would break compatibility with upstream, which is not an hard requirement, but it makes some things a bit easier.

For example our CI currently tests three different versions:

- odh main
- latest upstream tag
- upstream main

https://github.com/opendatahub-io/vllm-tgis-adapter/blob/main/.github/workflows/tests.yaml#L35-L37

Which allows us to proactively identify which upcoming changes break the vllm-tgis-adapter.

Changing the package name with `odh-vllm` would break this CI workflow. An easy fixw would be making `vllm` and `vllm-odh` optional (and conflicting?) extras, and selecting the package we want/need. We just need some time to figure out what the best approach here is.

**Pull request merged**
